import type { DeveloperLabFile } from './developerLab.ts'

export function gomokuDeveloperLabFiles(): DeveloperLabFile[] {
  const manifest = {
    format: 'dx-app/v2', id: 'dx-gomoku', version: '1.0.0', build: 10000, releaseChannel: 'dev', minSystemVersion: '0.1.0', dataVersion: 1, name: '五子棋', subtitle: '双人对弈',
    description: '适配 DX OS 主题与语言、支持保存对局的五子棋游戏。', entry: 'index.html',
    category: 'games', defaultSize: { width: 760, height: 680 },
    permissions: ['app.dx-gomoku.project.read', 'app.dx-gomoku.project.write'],
  }
  const html = `<!doctype html>
<html lang="zh-CN">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>五子棋</title><link rel="stylesheet" href="assets/app.css"></head>
<body><main class="game"><header><div><span class="eyebrow">DX GOMOKU</span><h1 data-i18n="title">五子棋</h1><p data-i18n="subtitle">双人对弈 · 五子连珠获胜</p></div><div id="turn" class="turn"></div></header><section class="stage"><canvas id="board" width="720" height="720" aria-label="五子棋棋盘"></canvas></section><footer><div id="status" class="status"></div><div class="actions"><button id="undo" data-i18n="undo">悔棋</button><button id="reset" class="primary" data-i18n="reset">重新开始</button></div></footer></main><script src="assets/app.js"></script></body>
</html>`
  const css = `:root{color-scheme:light;--bg:#f5f5f7;--panel:rgba(255,255,255,.82);--ink:#172033;--muted:#7a8494;--line:rgba(31,42,58,.12);--accent:#0a84ff;--board:#dcae66;--grid:#62441f}html[data-theme="dark"]{color-scheme:dark;--bg:#15181d;--panel:rgba(35,39,47,.88);--ink:#eef2f8;--muted:#969fac;--line:rgba(255,255,255,.12);--board:#a87439;--grid:#3e2814}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--ink);font-family:Inter,"PingFang SC",system-ui,sans-serif}body{padding:24px}.game{width:min(680px,100%);margin:auto;padding:22px;border:1px solid var(--line);border-radius:22px;background:var(--panel);box-shadow:0 26px 60px -42px rgba(12,24,40,.6);backdrop-filter:saturate(140%) blur(22px)}header,footer{display:flex;align-items:center;justify-content:space-between;gap:18px}.eyebrow{color:var(--accent);font-size:10px;font-weight:800;letter-spacing:1px}h1{margin:5px 0 2px;font-size:26px;letter-spacing:-.5px}p{margin:0;color:var(--muted);font-size:12px}.turn{display:flex;align-items:center;gap:8px;padding:8px 12px;border:1px solid var(--line);border-radius:999px;font-size:12px;font-weight:700}.turn i{width:14px;height:14px;border-radius:50%;box-shadow:0 2px 5px rgba(0,0,0,.3)}.stage{margin:20px 0;padding:12px;border-radius:18px;background:var(--board);box-shadow:inset 0 1px 0 rgba(255,255,255,.26)}canvas{display:block;width:100%;height:auto;cursor:pointer;touch-action:manipulation}.status{color:var(--muted);font-size:11px}.actions{display:flex;gap:8px}button{min-height:34px;padding:0 14px;border:1px solid var(--line);border-radius:10px;background:var(--panel);color:var(--ink);font:inherit;font-size:11px;font-weight:650;cursor:pointer}button:hover{filter:brightness(1.05)}button.primary{border:0;background:var(--accent);color:white}@media(max-width:520px){body{padding:10px}.game{padding:14px;border-radius:16px}header{align-items:flex-start}.turn{padding:6px 8px}footer{align-items:flex-start;flex-direction:column}.actions{width:100%}.actions button{flex:1}}`
  const js = `(function(){
class GomokuEngine{constructor(size=15){this.size=size;this.reset()}reset(){this.board=Array.from({length:this.size},()=>Array(this.size).fill(0));this.history=[];this.turn=1;this.winner=0}place(row,col){if(this.winner||row<0||col<0||row>=this.size||col>=this.size||this.board[row][col])return false;this.board[row][col]=this.turn;this.history.push([row,col,this.turn]);if(this.hasFive(row,col,this.turn))this.winner=this.turn;else this.turn=this.turn===1?2:1;return true}hasFive(row,col,color){return [[1,0],[0,1],[1,1],[1,-1]].some(([dr,dc])=>{let n=1;for(const sign of [-1,1]){let r=row+dr*sign,c=col+dc*sign;while(r>=0&&c>=0&&r<this.size&&c<this.size&&this.board[r][c]===color){n++;r+=dr*sign;c+=dc*sign}}return n>=5})}undo(){if(!this.history.length)return false;const [r,c,color]=this.history.pop();this.board[r][c]=0;this.turn=color;this.winner=0;return true}serialize(){return{size:this.size,board:this.board,history:this.history,turn:this.turn,winner:this.winner}}load(data){if(!data||data.size!==this.size||!Array.isArray(data.board))return false;this.board=data.board;this.history=Array.isArray(data.history)?data.history:[];this.turn=data.turn===2?2:1;this.winner=data.winner===1||data.winner===2?data.winner:0;return true}}
window.GomokuEngine=GomokuEngine;
const canvas=document.getElementById('board'),ctx=canvas.getContext('2d'),turnEl=document.getElementById('turn'),statusEl=document.getElementById('status'),engine=new GomokuEngine(15);let locale='zh-CN',seq=0;const pending=new Map();
const words={'zh-CN':{title:'五子棋',subtitle:'双人对弈 · 五子连珠获胜',undo:'悔棋',reset:'重新开始',black:'黑方',white:'白方',turn:'落子',win:'获胜',moves:'手'},'en-US':{title:'Gomoku',subtitle:'Two players · Connect five to win',undo:'Undo',reset:'New Game',black:'Black',white:'White',turn:'to move',win:'wins',moves:'moves'}};
function t(key){return words[locale.startsWith('zh')?'zh-CN':'en-US'][key]||key}function request(action,payload={}){return new Promise((resolve,reject)=>{const id='gomoku-'+(++seq);pending.set(id,{resolve,reject});parent.postMessage({dxos:'v1',type:'request',id,action,...payload},'*');setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(new Error('bridge timeout'))}},4000)})}
function applyContext(c){if(!c)return;document.documentElement.dataset.theme=c.appearance||'light';document.documentElement.lang=c.interfaceLocale||c.locale||'zh-CN';document.documentElement.dir=c.direction||'ltr';locale=document.documentElement.lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));render()}
addEventListener('message',e=>{const m=e.data;if(!m||m.dxos!=='v1')return;if(m.type==='system.context')applyContext(m.context);else if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.ok?p.resolve(m.result):p.reject(new Error(m.error||'bridge error'))}});
function drawStone(x,y,color,last){const cell=canvas.width/(engine.size+1),g=ctx.createRadialGradient(x-cell*.16,y-cell*.2,cell*.08,x,y,cell*.43);if(color===1){g.addColorStop(0,'#666');g.addColorStop(.35,'#222');g.addColorStop(1,'#050505')}else{g.addColorStop(0,'#fff');g.addColorStop(.55,'#f3f3f3');g.addColorStop(1,'#b9b9b9')}ctx.beginPath();ctx.arc(x,y,cell*.39,0,Math.PI*2);ctx.fillStyle=g;ctx.shadowColor='rgba(0,0,0,.28)';ctx.shadowBlur=6;ctx.shadowOffsetY=2;ctx.fill();ctx.shadowColor='transparent';if(last){ctx.beginPath();ctx.arc(x,y,cell*.09,0,Math.PI*2);ctx.fillStyle=color===1?'#ff5a52':'#e33';ctx.fill()}}
function render(){const size=canvas.width,cell=size/(engine.size+1);ctx.clearRect(0,0,size,size);ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--grid').trim()||'#62441f';ctx.lineWidth=1.35;for(let i=1;i<=engine.size;i++){ctx.beginPath();ctx.moveTo(cell,i*cell);ctx.lineTo(engine.size*cell,i*cell);ctx.stroke();ctx.beginPath();ctx.moveTo(i*cell,cell);ctx.lineTo(i*cell,engine.size*cell);ctx.stroke()}for(const r of [4,8,12])for(const c of [4,8,12]){ctx.beginPath();ctx.arc(c*cell,r*cell,3.5,0,Math.PI*2);ctx.fillStyle=ctx.strokeStyle;ctx.fill()}const last=engine.history[engine.history.length-1];engine.board.forEach((row,r)=>row.forEach((v,c)=>{if(v)drawStone((c+1)*cell,(r+1)*cell,v,!!last&&last[0]===r&&last[1]===c)}));const side=engine.winner||engine.turn,name=side===1?t('black'):t('white');turnEl.innerHTML='<i style="background:'+(side===1?'#111':'#fff')+'"></i>'+name+' · '+(engine.winner?t('win'):t('turn'));statusEl.textContent=engine.history.length+' '+t('moves')}
async function persist(){try{await request('project.write',{path:'games/current.json',content:JSON.stringify(engine.serialize())})}catch(e){console.warn('对局暂存失败',e.message)}}async function restore(){try{const r=await request('project.read',{path:'games/current.json'});if(r&&r.content)engine.load(JSON.parse(r.content))}catch(_){}render()}
canvas.addEventListener('click',e=>{const rect=canvas.getBoundingClientRect(),scale=canvas.width/rect.width,cell=canvas.width/(engine.size+1),col=Math.round((e.clientX-rect.left)*scale/cell)-1,row=Math.round((e.clientY-rect.top)*scale/cell)-1;if(engine.place(row,col)){render();void persist()}});document.getElementById('undo').onclick=()=>{if(engine.undo()){render();void persist()}};document.getElementById('reset').onclick=()=>{engine.reset();render();void persist()};
render();void restore();request('system.getContext').then(applyContext).catch(()=>{});
})();`
  return [
    { path: 'dx-app.json', content: JSON.stringify(manifest, null, 2) },
    { path: 'index.html', content: html },
    { path: 'assets/app.css', content: css },
    { path: 'assets/app.js', content: js },
  ]
}
